
package ru.study.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IDemoService", targetNamespace = "http://server.study.ru/", wsdlLocation = "http://localhost:8080/lab02-1.0-SNAPSHOT/demo?wsdl")
public class IDemoService
    extends Service
{

    private final static URL IDEMOSERVICE_WSDL_LOCATION;
    private final static WebServiceException IDEMOSERVICE_EXCEPTION;
    private final static QName IDEMOSERVICE_QNAME = new QName("http://server.study.ru/", "IDemoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab02-1.0-SNAPSHOT/demo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDEMOSERVICE_WSDL_LOCATION = url;
        IDEMOSERVICE_EXCEPTION = e;
    }

    public IDemoService() {
        super(__getWsdlLocation(), IDEMOSERVICE_QNAME);
    }

    public IDemoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDEMOSERVICE_QNAME, features);
    }

    public IDemoService(URL wsdlLocation) {
        super(wsdlLocation, IDEMOSERVICE_QNAME);
    }

    public IDemoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDEMOSERVICE_QNAME, features);
    }

    public IDemoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDemoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDemo
     */
    @WebEndpoint(name = "IDemoPort")
    public IDemo getIDemoPort() {
        return super.getPort(new QName("http://server.study.ru/", "IDemoPort"), IDemo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDemo
     */
    @WebEndpoint(name = "IDemoPort")
    public IDemo getIDemoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.study.ru/", "IDemoPort"), IDemo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDEMOSERVICE_EXCEPTION!= null) {
            throw IDEMOSERVICE_EXCEPTION;
        }
        return IDEMOSERVICE_WSDL_LOCATION;
    }

}
